
version: '3'

services:
  web:
    image: webdevops/php-nginx:ubuntu-16.04
    container_name: craft_web
    volumes:
      - ./app:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/web
    ports:
      - 8081:80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: craft_db
    environment:
      MYSQL_ROOT_PASSWORD: adminpwd
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpwd
      MYSQL_DATABASE: craftdb
